from django.core.management.base import BaseCommand

from liga.models import County, Place


class Command(BaseCommand):
    help = 'Loads all places to the database.'

    def handle(self, *args, **options):
        places = (
            ("KRAPINSKO-ZAGORSKA", "Kumrovec"),
            ("KRAPINSKO-ZAGORSKA", "Lobor"),
            ("KRAPINSKO-ZAGORSKA", "Mače"),
            ("KRAPINSKO-ZAGORSKA", "Marija Bistrica"),
            ("KRAPINSKO-ZAGORSKA", "Mihovljan"),
            ("KRAPINSKO-ZAGORSKA", "Novi Golubovec"),
            ("KRAPINSKO-ZAGORSKA", "Oroslavje"),
            ("KRAPINSKO-ZAGORSKA", "Petrovsko"),
            ("KRAPINSKO-ZAGORSKA", "Pregrada"),
            ("KRAPINSKO-ZAGORSKA", "Radoboj"),
            ("KRAPINSKO-ZAGORSKA", "Stubičke Toplice"),
            ("KRAPINSKO-ZAGORSKA", "Sveti Križ Začretje"),
            ("KRAPINSKO-ZAGORSKA", "Tuhelj"),
            ("KRAPINSKO-ZAGORSKA", "Veliko Trgovišće"),
            ("KRAPINSKO-ZAGORSKA", "Zabok"),
            ("KRAPINSKO-ZAGORSKA", "Zagorska Sela"),
            ("KRAPINSKO-ZAGORSKA", "Zlatar"),
            ("KRAPINSKO-ZAGORSKA", "Zlatar Bistrica"),
            ("SISAČKO-MOSLAVAČKA", "Donji Kukuruzari"),
            ("SISAČKO-MOSLAVAČKA", "Dvor"),
            ("SISAČKO-MOSLAVAČKA", "Glina"),
            ("SISAČKO-MOSLAVAČKA", "Gvozd"),
            ("SISAČKO-MOSLAVAČKA", "Hrvatska Dubica"),
            ("SISAČKO-MOSLAVAČKA", "Hrvatska Kostajnica"),
            ("SISAČKO-MOSLAVAČKA", "Jasenovac"),
            ("SISAČKO-MOSLAVAČKA", "Kutina"),
            ("SISAČKO-MOSLAVAČKA", "Lekenik"),
            ("SISAČKO-MOSLAVAČKA", "Lipovljani"),
            ("SISAČKO-MOSLAVAČKA", "Majur"),
            ("SISAČKO-MOSLAVAČKA", "Martinska Ves"),
            ("SISAČKO-MOSLAVAČKA", "Novska"),
            ("SISAČKO-MOSLAVAČKA", "Petrinja"),
            ("SISAČKO-MOSLAVAČKA", "Popovača"),
            ("SISAČKO-MOSLAVAČKA", "Sisak"),
            ("SISAČKO-MOSLAVAČKA", "Sunja"),
            ("SISAČKO-MOSLAVAČKA", "Topusko"),
            ("SISAČKO-MOSLAVAČKA", "Velika Ludina"),
            ("KARLOVAČKA", "Barilović"),
            ("KARLOVAČKA", "Bosiljevo"),
            ("KARLOVAČKA", "Cetingrad"),
            ("KARLOVAČKA", "Draganić"),
            ("KARLOVAČKA", "Generalski Stol"),
            ("KARLOVAČKA", "Josipdol"),
            ("KARLOVAČKA", "Kamanje"),
            ("KARLOVAČKA", "Krnjak"),
            ("KARLOVAČKA", "Lasinja"),
            ("KARLOVAČKA", "Netretić"),
            ("KARLOVAČKA", "Plaški"),
            ("KARLOVAČKA", "Rakovica"),
            ("KARLOVAČKA", "Ribnik"),
            ("KARLOVAČKA", "Saborsko"),
            ("KARLOVAČKA", "Tounj"),
            ("KARLOVAČKA", "Vojnić"),
            ("KARLOVAČKA", "Žakanje"),
            ("KARLOVAČKA", "Duga Resa"),
            ("KARLOVAČKA", "Karlovac"),
            ("KARLOVAČKA", "Ogulin"),
            ("KARLOVAČKA", "Ozalj"),
            ("KARLOVAČKA", "Slunj"),
            ("LIČKO-SENJSKA", "Brinje"),
            ("LIČKO-SENJSKA", "Donji Lapac"),
            ("LIČKO-SENJSKA", "Gospić"),
            ("LIČKO-SENJSKA", "Karlobag"),
            ("LIČKO-SENJSKA", "Lovinac"),
            ("LIČKO-SENJSKA", "Novalja"),
            ("LIČKO-SENJSKA", "Otočac"),
            ("LIČKO-SENJSKA", "Perušić"),
            ("LIČKO-SENJSKA", "Plitvička Jezera"),
            ("LIČKO-SENJSKA", "Senj"),
            ("LIČKO-SENJSKA", "Udbina"),
            ("LIČKO-SENJSKA", "Vrhovine"),
            ("VARAŽDINSKA", "Bednja"),
            ("VARAŽDINSKA", "Beretinec"),
            ("VARAŽDINSKA", "Breznica"),
            ("VARAŽDINSKA", "Breznički Hum"),
            ("VARAŽDINSKA", "Cestica"),
            ("VARAŽDINSKA", "Donja Voća"),
            ("VARAŽDINSKA", "Gornji Kneginec"),
            ("VARAŽDINSKA", "Jalžabet"),
            ("VARAŽDINSKA", "Ivanec"),
            ("VARAŽDINSKA", "Klenovnik"),
            ("VARAŽDINSKA", "Ljubešćica"),
            ("VARAŽDINSKA", "Lepoglava"),
            ("VARAŽDINSKA", "Ludbreg"),
            ("VARAŽDINSKA", "Mali Bukovec"),
            ("VARAŽDINSKA", "Martijanec"),
            ("VARAŽDINSKA", "Maruševec"),
            ("VARAŽDINSKA", "Novi Marof"),
            ("VARAŽDINSKA", "Petrijanec"),
            ("VARAŽDINSKA", "Sračinec"),
            ("VARAŽDINSKA", "Sveti Đurđ"),
            ("VARAŽDINSKA", "Sveti Ilija"),
            ("VARAŽDINSKA", "Trnovec Bartolovečki"),
            ("VARAŽDINSKA", "Varaždin"),
            ("VARAŽDINSKA", "Varaždinske Toplice"),
            ("VARAŽDINSKA", "Veliki Bukovec"),
            ("VARAŽDINSKA", "Vidovec"),
            ("VARAŽDINSKA", "Vinica"),
            ("VARAŽDINSKA", "Visoko"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Drnje"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Đelekovec"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Đurđevac"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Ferdinandovac"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Gola"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Gornja Rijeka"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Hlebine"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Kalinovac"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Kalnik"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Kloštar Podravski"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Koprivnički Bregi"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Koprivnica"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Koprivnički Ivanec"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Legrad"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Molve"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Novigrad Podravski"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Novo Virje"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Peteranec"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Podravske Sesvete"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Rasinja"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Sokolovac"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Sveti Ivan Žabno"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Sveti Petar Orehovec"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Virje"),
            ("KOPRIVNIČKO-KRIŽEVAČKA", "Križevci"),
            ("BJELOVARSKO-BILOGORSKA", "Berek"),
            ("BJELOVARSKO-BILOGORSKA", "Bjelovar"),
            ("BJELOVARSKO-BILOGORSKA", "Čazma"),
            ("BJELOVARSKO-BILOGORSKA", "Daruvar"),
            ("BJELOVARSKO-BILOGORSKA", "Dežanovac"),
            ("BJELOVARSKO-BILOGORSKA", "Đulovac"),
            ("BJELOVARSKO-BILOGORSKA", "Garešnica"),
            ("BJELOVARSKO-BILOGORSKA", "Grubišno Polje"),
            ("BJELOVARSKO-BILOGORSKA", "Hercegovac"),
            ("BJELOVARSKO-BILOGORSKA", "Ivanska"),
            ("BJELOVARSKO-BILOGORSKA", "Kapela"),
            ("BJELOVARSKO-BILOGORSKA", "Končanica"),
            ("BJELOVARSKO-BILOGORSKA", "Nova Rača"),
            ("BJELOVARSKO-BILOGORSKA", "Rovišće"),
            ("BJELOVARSKO-BILOGORSKA", "Severin"),
            ("BJELOVARSKO-BILOGORSKA", "Sirač"),
            ("BJELOVARSKO-BILOGORSKA", "Šandrovac"),
            ("BJELOVARSKO-BILOGORSKA", "Štefanje"),
            ("BJELOVARSKO-BILOGORSKA", "Velika Pisanica"),
            ("BJELOVARSKO-BILOGORSKA", "Velika Trnovitica"),
            ("BJELOVARSKO-BILOGORSKA", "Veliki Grđevac"),
            ("BJELOVARSKO-BILOGORSKA", "Veliko Trojstvo"),
            ("BJELOVARSKO-BILOGORSKA", "Zrinski Topolovac"),
            ("PRIMORSKO-GORANSKA", "Bakar"),
            ("PRIMORSKO-GORANSKA", "Baška"),
            ("PRIMORSKO-GORANSKA", "Brod Moravice"),
            ("PRIMORSKO-GORANSKA", "Cres"),
            ("PRIMORSKO-GORANSKA", "Crikvenica"),
            ("PRIMORSKO-GORANSKA", "Čabar"),
            ("PRIMORSKO-GORANSKA", "Čavle"),
            ("PRIMORSKO-GORANSKA", "Delnice"),
            ("PRIMORSKO-GORANSKA", "Dobrinj"),
            ("PRIMORSKO-GORANSKA", "Fužine"),
            ("PRIMORSKO-GORANSKA", "Jelenje"),
            ("PRIMORSKO-GORANSKA", "Kastav"),
            ("PRIMORSKO-GORANSKA", "Klana"),
            ("PRIMORSKO-GORANSKA", "Kostrena"),
            ("PRIMORSKO-GORANSKA", "Kraljevica"),
            ("PRIMORSKO-GORANSKA", "Krk"),
            ("PRIMORSKO-GORANSKA", "Lokve"),
            ("PRIMORSKO-GORANSKA", "Lopar"),
            ("PRIMORSKO-GORANSKA", "Lovran"),
            ("PRIMORSKO-GORANSKA", "Mali Lošinj"),
            ("PRIMORSKO-GORANSKA", "Malinska-Dubašnica"),
            ("PRIMORSKO-GORANSKA", "Matulji"),
            ("PRIMORSKO-GORANSKA", "Mošćenička Draga"),
            ("PRIMORSKO-GORANSKA", "Mrkopalj"),
            ("PRIMORSKO-GORANSKA", "Novi Vinodolski"),
            ("PRIMORSKO-GORANSKA", "Omišalj"),
            ("PRIMORSKO-GORANSKA", "Opatija"),
            ("PRIMORSKO-GORANSKA", "Punat"),
            ("PRIMORSKO-GORANSKA", "Rab"),
            ("PRIMORSKO-GORANSKA", "Ravna Gora"),
            ("PRIMORSKO-GORANSKA", "Rijeka"),
            ("PRIMORSKO-GORANSKA", "Skrad"),
            ("PRIMORSKO-GORANSKA", "Vinodolska općina"),
            ("PRIMORSKO-GORANSKA", "Viškovo"),
            ("PRIMORSKO-GORANSKA", "Vrbnik"),
            ("PRIMORSKO-GORANSKA", "Vrbovsko"),
            ("VIROVITIČKO-PODRAVSKA", "Crnac"),
            ("VIROVITIČKO-PODRAVSKA", "Čačinci"),
            ("VIROVITIČKO-PODRAVSKA", "Čađavica"),
            ("VIROVITIČKO-PODRAVSKA", "Gradina"),
            ("VIROVITIČKO-PODRAVSKA", "Lukač"),
            ("VIROVITIČKO-PODRAVSKA", "Mikleuš"),
            ("VIROVITIČKO-PODRAVSKA", "Nova Bukovica"),
            ("VIROVITIČKO-PODRAVSKA", "Orahovica"),
            ("VIROVITIČKO-PODRAVSKA", "Pitomača"),
            ("VIROVITIČKO-PODRAVSKA", "Slatina"),
            ("VIROVITIČKO-PODRAVSKA", "Sopje"),
            ("VIROVITIČKO-PODRAVSKA", "Suhopolje"),
            ("VIROVITIČKO-PODRAVSKA", "Špišić Bukovica"),
            ("VIROVITIČKO-PODRAVSKA", "Virovitica"),
            ("VIROVITIČKO-PODRAVSKA", "Voćin"),
            ("VIROVITIČKO-PODRAVSKA", "Zdenci"),
            ("POŽEŠKO-SLAVONSKA", "Brestovac"),
            ("POŽEŠKO-SLAVONSKA", "Čaglin"),
            ("POŽEŠKO-SLAVONSKA", "Jakšić"),
            ("POŽEŠKO-SLAVONSKA", "Kaptol"),
            ("POŽEŠKO-SLAVONSKA", "Kutjevo"),
            ("POŽEŠKO-SLAVONSKA", "Lipik"),
            ("POŽEŠKO-SLAVONSKA", "Pakrac"),
            ("POŽEŠKO-SLAVONSKA", "Pleternica"),
            ("POŽEŠKO-SLAVONSKA", "Požega"),
            ("POŽEŠKO-SLAVONSKA", "Velika"),
            ("BRODSKO-POSAVSKA", "Bebrina"),
            ("BRODSKO-POSAVSKA", "Brodski Stupnik"),
            ("BRODSKO-POSAVSKA", "Bukovlje"),
            ("BRODSKO-POSAVSKA", "Cernik"),
            ("BRODSKO-POSAVSKA", "Davor"),
            ("BRODSKO-POSAVSKA", "Donji Andrijevci"),
            ("BRODSKO-POSAVSKA", "Dragalić"),
            ("BRODSKO-POSAVSKA", "Garčin"),
            ("BRODSKO-POSAVSKA", "Gornja Vrba"),
            ("BRODSKO-POSAVSKA", "Gornji Bogićevci"),
            ("BRODSKO-POSAVSKA", "Gundinci"),
            ("BRODSKO-POSAVSKA", "Klakar"),
            ("BRODSKO-POSAVSKA", "Nova Gradiška"),
            ("BRODSKO-POSAVSKA", "Nova Kapela"),
            ("BRODSKO-POSAVSKA", "Okučani"),
            ("BRODSKO-POSAVSKA", "Oprisavci"),
            ("BRODSKO-POSAVSKA", "Oriovac"),
            ("BRODSKO-POSAVSKA", "Podcrkavlje"),
            ("BRODSKO-POSAVSKA", "Rešetari"),
            ("BRODSKO-POSAVSKA", "Sibinj"),
            ("BRODSKO-POSAVSKA", "Sikirevci"),
            ("BRODSKO-POSAVSKA", "Slavonski Brod"),
            ("BRODSKO-POSAVSKA", "Slavonski Šamac"),
            ("BRODSKO-POSAVSKA", "Stara Gradiška"),
            ("BRODSKO-POSAVSKA", "Staro Petrovo Selo"),
            ("BRODSKO-POSAVSKA", "Velika Kopanica"),
            ("BRODSKO-POSAVSKA", "Vrbje"),
            ("BRODSKO-POSAVSKA", "Vrpolje"),
            ("ZADARSKA", "Benkovac"),
            ("ZADARSKA", "Bibinje"),
            ("ZADARSKA", "Biograd na Moru"),
            ("ZADARSKA", "Galovac"),
            ("ZADARSKA", "Gračac"),
            ("ZADARSKA", "Jasenice"),
            ("ZADARSKA", "Kali"),
            ("ZADARSKA", "Kolan"),
            ("ZADARSKA", "Kukljica"),
            ("ZADARSKA", "Lišane Ostrovičke"),
            ("ZADARSKA", "Nin"),
            ("ZADARSKA", "Novigrad"),
            ("ZADARSKA", "Obrovac"),
            ("ZADARSKA", "Pag"),
            ("ZADARSKA", "Pakoštane"),
            ("ZADARSKA", "Pašman"),
            ("ZADARSKA", "Polača"),
            ("ZADARSKA", "Poličnik"),
            ("ZADARSKA", "Posedarje"),
            ("ZADARSKA", "Povljana"),
            ("ZADARSKA", "Preko"),
            ("ZADARSKA", "Privlaka"),
            ("ZADARSKA", "Ražanac"),
            ("ZADARSKA", "Sali"),
            ("ZADARSKA", "Stankovci"),
            ("ZADARSKA", "Starigrad"),
            ("ZADARSKA", "Sukošan"),
            ("ZADARSKA", "Sveti Filip i Jakov"),
            ("ZADARSKA", "Škabrnja"),
            ("ZADARSKA", "Tkon"),
            ("ZADARSKA", "Vir"),
            ("ZADARSKA", "Vrsi"),
            ("ZADARSKA", "Zadar"),
            ("ZADARSKA", "Zemunik Donji"),
            ("OSJEČKO-BARANJSKA", "Antunovac"),
            ("OSJEČKO-BARANJSKA", "Beli Manastir"),
            ("OSJEČKO-BARANJSKA", "Belišće"),
            ("OSJEČKO-BARANJSKA", "Bilje"),
            ("OSJEČKO-BARANJSKA", "Bizovac"),
            ("OSJEČKO-BARANJSKA", "Čeminac"),
            ("OSJEČKO-BARANJSKA", "Čepin"),
            ("OSJEČKO-BARANJSKA", "Darda"),
            ("OSJEČKO-BARANJSKA", "Donja Motičina"),
            ("OSJEČKO-BARANJSKA", "Donji Miholjac"),
            ("OSJEČKO-BARANJSKA", "Draž"),
            ("OSJEČKO-BARANJSKA", "Drenje"),
            ("OSJEČKO-BARANJSKA", "Đakovo"),
            ("OSJEČKO-BARANJSKA", "Đurđenovac"),
            ("OSJEČKO-BARANJSKA", "Erdut"),
            ("OSJEČKO-BARANJSKA", "Ernestinovo"),
            ("OSJEČKO-BARANJSKA", "Feričanci"),
            ("OSJEČKO-BARANJSKA", "Gorjani"),
            ("OSJEČKO-BARANJSKA", "Jagodnjak"),
            ("OSJEČKO-BARANJSKA", "Kneževi Vinogradi"),
            ("OSJEČKO-BARANJSKA", "Koška"),
            ("OSJEČKO-BARANJSKA", "Levanjska Varoš"),
            ("OSJEČKO-BARANJSKA", "Magadenovac"),
            ("OSJEČKO-BARANJSKA", "Marijanci"),
            ("OSJEČKO-BARANJSKA", "Našice"),
            ("OSJEČKO-BARANJSKA", "Osijek"),
            ("OSJEČKO-BARANJSKA", "Petlovac"),
            ("OSJEČKO-BARANJSKA", "Petrijevci"),
            ("OSJEČKO-BARANJSKA", "Podgorač"),
            ("OSJEČKO-BARANJSKA", "Podravska Moslavina"),
            ("OSJEČKO-BARANJSKA", "Popovac"),
            ("OSJEČKO-BARANJSKA", "Punitovci"),
            ("OSJEČKO-BARANJSKA", "Satnica Đakovačka"),
            ("OSJEČKO-BARANJSKA", "Semeljci"),
            ("OSJEČKO-BARANJSKA", "Strizivojna"),
            ("OSJEČKO-BARANJSKA", "Šodolovci"),
            ("OSJEČKO-BARANJSKA", "Trnava"),
            ("OSJEČKO-BARANJSKA", "Valpovo"),
            ("OSJEČKO-BARANJSKA", "Viljevo"),
            ("OSJEČKO-BARANJSKA", "Viškovci"),
            ("OSJEČKO-BARANJSKA", "Vladislavci"),
            ("OSJEČKO-BARANJSKA", "Vuka"),
            ("DUBROVAČKO-NERETVANSKA", "Blato"),
            ("DUBROVAČKO-NERETVANSKA", "Dubrovačko primorje"),
            ("DUBROVAČKO-NERETVANSKA", "Dubrovnik"),
            ("DUBROVAČKO-NERETVANSKA", "Janjina"),
            ("DUBROVAČKO-NERETVANSKA", "Konavle"),
            ("DUBROVAČKO-NERETVANSKA", "Korčula"),
            ("DUBROVAČKO-NERETVANSKA", "Kula Norinska"),
            ("DUBROVAČKO-NERETVANSKA", "Lastovo"),
            ("DUBROVAČKO-NERETVANSKA", "Lumbarda"),
            ("DUBROVAČKO-NERETVANSKA", "Metković"),
            ("DUBROVAČKO-NERETVANSKA", "Mljet"),
            ("DUBROVAČKO-NERETVANSKA", "Opuzen"),
            ("DUBROVAČKO-NERETVANSKA", "Orebić"),
            ("DUBROVAČKO-NERETVANSKA", "Ploče"),
            ("DUBROVAČKO-NERETVANSKA", "Pojezerje"),
            ("DUBROVAČKO-NERETVANSKA", "Slivno"),
            ("DUBROVAČKO-NERETVANSKA", "Smokvica"),
            ("DUBROVAČKO-NERETVANSKA", "Ston"),
            ("DUBROVAČKO-NERETVANSKA", "Trpanj"),
            ("DUBROVAČKO-NERETVANSKA", "Vela Luka"),
            ("DUBROVAČKO-NERETVANSKA", "Zažablje"),
            ("DUBROVAČKO-NERETVANSKA", "Župa dubrovačka"),
            ("ŠIBENSKO-KNINSKA", "Bilice"),
            ("ŠIBENSKO-KNINSKA", "Biskupija"),
            ("ŠIBENSKO-KNINSKA", "Civljane"),
            ("ŠIBENSKO-KNINSKA", "Drniš"),
            ("ŠIBENSKO-KNINSKA", "Ervenik"),
            ("ŠIBENSKO-KNINSKA", "Kijevo"),
            ("ŠIBENSKO-KNINSKA", "Kistanje"),
            ("ŠIBENSKO-KNINSKA", "Knin"),
            ("ŠIBENSKO-KNINSKA", "Murter-Kornati"),
            ("ŠIBENSKO-KNINSKA", "Pirovac"),
            ("ŠIBENSKO-KNINSKA", "Primošten"),
            ("ŠIBENSKO-KNINSKA", "Promina"),
            ("ŠIBENSKO-KNINSKA", "Rogoznica"),
            ("ŠIBENSKO-KNINSKA", "Ružić"),
            ("ŠIBENSKO-KNINSKA", "Skradin"),
            ("ŠIBENSKO-KNINSKA", "Šibenik"),
            ("ŠIBENSKO-KNINSKA", "Tisno"),
            ("ŠIBENSKO-KNINSKA", "Tribunj"),
            ("ŠIBENSKO-KNINSKA", "Unešić"),
            ("ŠIBENSKO-KNINSKA", "Vodice"),
            ("VUKOVARSKO-SRIJEMSKA", "Andrijaševci"),
            ("VUKOVARSKO-SRIJEMSKA", "Babina Greda"),
            ("VUKOVARSKO-SRIJEMSKA", "Bogdanovci"),
            ("VUKOVARSKO-SRIJEMSKA", "Borovo"),
            ("VUKOVARSKO-SRIJEMSKA", "Bošnjaci"),
            ("VUKOVARSKO-SRIJEMSKA", "Cerna"),
            ("VUKOVARSKO-SRIJEMSKA", "Drenovci"),
            ("VUKOVARSKO-SRIJEMSKA", "Gradište"),
            ("VUKOVARSKO-SRIJEMSKA", "Gunja"),
            ("VUKOVARSKO-SRIJEMSKA", "Ilok"),
            ("VUKOVARSKO-SRIJEMSKA", "Ivankovo"),
            ("VUKOVARSKO-SRIJEMSKA", "Jarmina"),
            ("VUKOVARSKO-SRIJEMSKA", "Lovas"),
            ("VUKOVARSKO-SRIJEMSKA", "Markušica"),
            ("VUKOVARSKO-SRIJEMSKA", "Negoslavci"),
            ("VUKOVARSKO-SRIJEMSKA", "Nijemci"),
            ("VUKOVARSKO-SRIJEMSKA", "Nuštar"),
            ("VUKOVARSKO-SRIJEMSKA", "Otok"),
            ("VUKOVARSKO-SRIJEMSKA", "Privlaka"),
            ("VUKOVARSKO-SRIJEMSKA", "Stari Jankovci"),
            ("VUKOVARSKO-SRIJEMSKA", "Stari Mikanovci"),
            ("VUKOVARSKO-SRIJEMSKA", "Štitar"),
            ("VUKOVARSKO-SRIJEMSKA", "Tompojevci"),
            ("VUKOVARSKO-SRIJEMSKA", "Tordinci"),
            ("VUKOVARSKO-SRIJEMSKA", "Tovarnik"),
            ("VUKOVARSKO-SRIJEMSKA", "Trpinja"),
            ("VUKOVARSKO-SRIJEMSKA", "Vinkovci"),
            ("VUKOVARSKO-SRIJEMSKA", "Vođinci"),
            ("VUKOVARSKO-SRIJEMSKA", "Vrbanja"),
            ("VUKOVARSKO-SRIJEMSKA", "Vukovar"),
            ("VUKOVARSKO-SRIJEMSKA", "Županja"),
            ("SPLITSKO-DALMATINSKA", "Baška Voda"),
            ("SPLITSKO-DALMATINSKA", "Bol"),
            ("SPLITSKO-DALMATINSKA", "Brela"),
            ("SPLITSKO-DALMATINSKA", "Cista Provo"),
            ("SPLITSKO-DALMATINSKA", "Dicmo"),
            ("SPLITSKO-DALMATINSKA", "Dugi Rat"),
            ("SPLITSKO-DALMATINSKA", "Dugopolje"),
            ("SPLITSKO-DALMATINSKA", "Gradac"),
            ("SPLITSKO-DALMATINSKA", "Hrvace"),
            ("SPLITSKO-DALMATINSKA", "Hvar"),
            ("SPLITSKO-DALMATINSKA", "Imotski"),
            ("SPLITSKO-DALMATINSKA", "Jelsa"),
            ("SPLITSKO-DALMATINSKA", "Kaštela"),
            ("SPLITSKO-DALMATINSKA", "Klis"),
            ("SPLITSKO-DALMATINSKA", "Komiža"),
            ("SPLITSKO-DALMATINSKA", "Lećevica"),
            ("SPLITSKO-DALMATINSKA", "Lokvičići"),
            ("SPLITSKO-DALMATINSKA", "Lovreć"),
            ("SPLITSKO-DALMATINSKA", "Makarska"),
            ("SPLITSKO-DALMATINSKA", "Marina"),
            ("SPLITSKO-DALMATINSKA", "Milna"),
            ("SPLITSKO-DALMATINSKA", "Muć"),
            ("SPLITSKO-DALMATINSKA", "Nerežišća"),
            ("SPLITSKO-DALMATINSKA", "Okrug"),
            ("SPLITSKO-DALMATINSKA", "Omiš"),
            ("SPLITSKO-DALMATINSKA", "Otok"),
            ("SPLITSKO-DALMATINSKA", "Podbablje"),
            ("SPLITSKO-DALMATINSKA", "Podgora"),
            ("SPLITSKO-DALMATINSKA", "Podstrana"),
            ("SPLITSKO-DALMATINSKA", "Postira"),
            ("SPLITSKO-DALMATINSKA", "Prgomet"),
            ("SPLITSKO-DALMATINSKA", "Primorski Dolac"),
            ("SPLITSKO-DALMATINSKA", "Proložac"),
            ("SPLITSKO-DALMATINSKA", "Pučišća"),
            ("SPLITSKO-DALMATINSKA", "Runovići"),
            ("SPLITSKO-DALMATINSKA", "Seget"),
            ("SPLITSKO-DALMATINSKA", "Selca"),
            ("SPLITSKO-DALMATINSKA", "Sinj"),
            ("SPLITSKO-DALMATINSKA", "Solin"),
            ("SPLITSKO-DALMATINSKA", "Split"),
            ("SPLITSKO-DALMATINSKA", "Stari Grad"),
            ("SPLITSKO-DALMATINSKA", "Sućuraj"),
            ("SPLITSKO-DALMATINSKA", "Supetar"),
            ("SPLITSKO-DALMATINSKA", "Sutivan"),
            ("SPLITSKO-DALMATINSKA", "Šestanovac"),
            ("SPLITSKO-DALMATINSKA", "Šolta"),
            ("SPLITSKO-DALMATINSKA", "Trilj"),
            ("SPLITSKO-DALMATINSKA", "Trogir"),
            ("SPLITSKO-DALMATINSKA", "Tučepi"),
            ("SPLITSKO-DALMATINSKA", "Vis"),
            ("SPLITSKO-DALMATINSKA", "Vrgorac"),
            ("SPLITSKO-DALMATINSKA", "Vrlika"),
            ("SPLITSKO-DALMATINSKA", "Zadvarje"),
            ("SPLITSKO-DALMATINSKA", "Zagvozd"),
            ("SPLITSKO-DALMATINSKA", "Zmijavci"),
            ("ISTARSKA", "Bale-Valle"),
            ("ISTARSKA", "Barban"),
            ("ISTARSKA", "Brtonigla-Verteneglio"),
            ("ISTARSKA", "Buje-Buie"),
            ("ISTARSKA", "Buzet"),
            ("ISTARSKA", "Cerovlje"),
            ("ISTARSKA", "Fažana-Fasana"),
            ("ISTARSKA", "Funtana-Fontane"),
            ("ISTARSKA", "Gračišće"),
            ("ISTARSKA", "Grožnjan-Grisignana"),
            ("ISTARSKA", "Kanfanar"),
            ("ISTARSKA", "Karojba"),
            ("ISTARSKA", "Kaštelir-Labinci-Castelliere-S. Domenica"),
            ("ISTARSKA", "Kršan"),
            ("ISTARSKA", "Labin"),
            ("ISTARSKA", "Lanišće"),
            ("ISTARSKA", "Ližnjan-Lisignano"),
            ("ISTARSKA", "Lupoglav"),
            ("ISTARSKA", "Marčana"),
            ("ISTARSKA", "Medulin"),
            ("ISTARSKA", "Motovun-Montona"),
            ("ISTARSKA", "Novigrad-Cittanova"),
            ("ISTARSKA", "Oprtalj-Portole"),
            ("ISTARSKA", "Pazin"),
            ("ISTARSKA", "Pićan"),
            ("ISTARSKA", "Poreč-Parenzo"),
            ("ISTARSKA", "Pula-Pola"),
            ("ISTARSKA", "Raša"),
            ("ISTARSKA", "Rovinj-Rovigno"),
            ("ISTARSKA", "Sveta Nedelja"),
            ("ISTARSKA", "Sveti Lovreč"),
            ("ISTARSKA", "Sveti Petar u Šumi"),
            ("ISTARSKA", "Svetvinčenat"),
            ("ISTARSKA", "Tar-Vabriga-Torre Abrega"),
            ("ISTARSKA", "Tinjan"),
            ("ISTARSKA", "Umag-Umago"),
            ("ISTARSKA", "Višnjan-Visignano"),
            ("ISTARSKA", "Vižinada-Visinada"),
            ("ISTARSKA", "Vodnjan-Dignano"),
            ("ISTARSKA", "Vrsar-Orsera"),
            ("ISTARSKA", "Žminj"),
            ("MEĐIMURSKA", "Belica"),
            ("MEĐIMURSKA", "Čakovec"),
            ("MEĐIMURSKA", "Dekanovec"),
            ("MEĐIMURSKA", "Domašinec"),
            ("MEĐIMURSKA", "Donja Dubrava"),
            ("MEĐIMURSKA", "Donji Kraljevec"),
            ("MEĐIMURSKA", "Donji Vidovec"),
            ("MEĐIMURSKA", "Goričan"),
            ("MEĐIMURSKA", "Gornji Mihaljevec"),
            ("MEĐIMURSKA", "Kotoriba"),
            ("MEĐIMURSKA", "Mala Subotica"),
            ("MEĐIMURSKA", "Mursko Središće"),
            ("MEĐIMURSKA", "Nedelišće"),
            ("MEĐIMURSKA", "Orehovica"),
            ("MEĐIMURSKA", "Podturen"),
            ("MEĐIMURSKA", "Prelog"),
            ("MEĐIMURSKA", "Pribislavec"),
            ("MEĐIMURSKA", "Selnica"),
            ("MEĐIMURSKA", "Strahoninec"),
            ("MEĐIMURSKA", "Sveta Marija"),
            ("MEĐIMURSKA", "Sveti Juraj na Bregu"),
            ("MEĐIMURSKA", "Sveti Martin na Muri"),
            ("MEĐIMURSKA", "Šenkovec"),
            ("MEĐIMURSKA", "Štrigova"),
            ("MEĐIMURSKA", "Vratišinec"),
            ("GRAD ZAGREB", "Zagreb")
         )
        for place_data in places:
            place = Place()
            place.name = place_data[1]
            try:
                county = County.objects.filter(name_lower=place_data[0].lower())
                place.county = county.first()

                place.save()

                self.stdout.write(self.style.SUCCESS('Successfully saved place "%s / %s"' % (place.name, place.county.name)))
            except Exception as e:
                self.stdout.write(self.style.ERROR('Error saving place "%s / %s"' % (place.name, e)))
