# Generated by Django 3.2.12 on 2022-03-11 10:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=200)),
                ('topic', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_lower', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_lower', models.CharField(max_length=200)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.county')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('rank', models.IntegerField()),
                ('performance', models.DecimalField(decimal_places=2, max_digits=4)),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.competition')),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.county')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.school')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('name_lower', models.CharField(max_length=200)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='liga.county')),
            ],
        ),
    ]
